title: Zhenxing Guo
logo: /assets/img/Zhenxing.jpg
description: Ph.D. student of the Department of Biostatistics and Bioinformatics, Emory University
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
address:
  - line: 1518 Clifton RD NE
  - line: Atlanta, GA 30322, USA
